#单张彩票的价格
price: 50.0

#获得一等奖（三位全匹配）的奖励
firstprize: 10000.0
#获得二等奖（连续两位对应匹配）的奖励
secondprize: 1000.0
#获得三等奖（一位对应匹配）的奖励
thirdprize: 100.0

#彩票起始期数
lotteryid: 1

#每期彩票最多购买张数
max: 10000

#每期彩票间隔时间（秒）
roundsecond: 300
